name: py3tf
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.1=py36_0
  - astor=0.7.1=py36_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py36_0
  - gast=0.2.2=py36_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - intel-openmp=2019.4=243
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.8.0=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markdown=3.1.1=py36_0
  - mkl=2019.4=243
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.4=py36h7e9f1db_0
  - numpy-base=1.16.4=py36hde5b4d6_0
  - openssl=1.1.1c=h7b6447c_1
  - pip=19.1.1=py36_0
  - protobuf=3.8.0=py36he6710b0_0
  - python=3.6.8=h0371630_0
  - readline=7.0=h7b6447c_5
  - scipy=1.2.1=py36h7c811a0_0
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=mkl_py36h69b6ba0_0
  - tensorflow-base=1.12.0=mkl_py36h3c3e929_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
prefix: /home/zhangyuge/anaconda3/envs/py3tf

